Repository getninjas/jason, pull requests merged in 2018-06, with the labels that each got.

#15 Fixed keyboard submit
  spec/components/Factory.spec.js
  spec/components/Field.spec.js
  spec/components/Form/__snapshots__/index.spec.js.snap
  spec/components/Input.spec.js
  spec/components/Select.spec.js
  spec/components/Step.spec.js
  spec/components/TextArea.spec.js
  spec/components/Zipcode.spec.js
  spec/helpers/zipcode.spec.js
  src/components/Factory.js
  src/components/Form/index.js
  src/components/Form/validation.js
  src/components/Input.js
  src/components/Select.js
  src/components/Step.js
  src/components/TextArea.js
  src/components/Zipcode.js
  src/form.json
  src/helpers/zipcode.js
  src/index.dev.js
Labels: bug, to review

#16 Change error response
  src/components/Form/index.js
Labels: bug

#19 decreased minimum length for required text input
  README.md
  spec/components/Form/__snapshots__/index.spec.js.snap
  spec/components/__snapshots__/Field.spec.js.snap
  spec/components/__snapshots__/Input.spec.js.snap
  spec/components/__snapshots__/Step.spec.js.snap
  src/components/Input.js
Labels: enhancement
