Repository getninjas/jason, pull requests merged in 2018-05, with the labels that each got.

#2 Render UI via JSON form data
  .codeclimate.yml
  .eslintrc.json
  .travis.yml
  build/main.js
  package-lock.json
  package.json
  public/index.html
  spec/App.spec.js
  spec/components/Breadcrumb.spec.js
  spec/components/Button.spec.js
  spec/components/Factory.spec.js
  spec/components/Field.spec.js
  spec/components/Form.spec.js
  spec/components/Input.spec.js
  spec/components/Select.spec.js
  spec/components/Step.spec.js
  spec/components/TextArea.spec.js
  spec/components/__snapshots__/Breadcrumb.spec.js.snap
  spec/components/__snapshots__/Button.spec.js.snap
  spec/components/__snapshots__/Field.spec.js.snap
  spec/components/__snapshots__/Form.spec.js.snap
  spec/components/__snapshots__/Input.spec.js.snap
  spec/components/__snapshots__/Select.spec.js.snap
  spec/components/__snapshots__/Step.spec.js.snap
  spec/components/__snapshots__/TextArea.spec.js.snap
  spec/enzymeConfig.js
  src/App.jsx
  src/components/Breadcrumb.jsx
  src/components/Button.jsx
  src/components/Factory.jsx
  src/components/Field.jsx
  src/components/Form.jsx
  src/components/Input.jsx
  src/components/Select.jsx
  src/components/StartText.jsx
  src/components/Step.jsx
  src/components/TextArea.jsx
  src/form.json
  src/index.dev.js
  src/index.js
Labels: to review

#3 Form validation
  package-lock.json
  package.json
  public/index.html
  spec/App.spec.js
  spec/components/Breadcrumb.spec.js
  spec/components/Button.spec.js
  spec/components/Factory.spec.js
  spec/components/Field.spec.js
  spec/components/Form.spec.js
  spec/components/Form/__snapshots__/index.spec.js.snap
  spec/components/Form/index.spec.js
  spec/components/Form/validation.spec.js
  spec/components/Input.spec.js
  spec/components/Select.spec.js
  spec/components/Step.spec.js
  spec/components/TextArea.spec.js
  spec/components/__snapshots__/Button.spec.js.snap
  spec/components/__snapshots__/Field.spec.js.snap
  spec/components/__snapshots__/Form.spec.js.snap
  spec/components/__snapshots__/Input.spec.js.snap
  spec/components/__snapshots__/Select.spec.js.snap
  spec/components/__snapshots__/Step.spec.js.snap
  spec/components/__snapshots__/TextArea.spec.js.snap
  spec/enzymeConfig.js
  spec/helper.js
  spec/jsdomConfig.js
  src/App.jsx
  src/components/Factory.jsx
  src/components/Field.jsx
  src/components/Form.jsx
  src/components/Form/index.jsx
  src/components/Form/validation.js
  src/components/Input.jsx
  src/components/Select.jsx
  src/components/Step.jsx
  src/components/TextArea.jsx
  src/form.json
  src/helpers/errorMessages.js
  src/helpers/input.js
Labels: feature, to review

#5 Change extension JSX to JS
  src/App.js
  src/components/Breadcrumb.js
  src/components/Button.js
  src/components/Factory.js
  src/components/Field.js
  src/components/Form/index.js
  src/components/Input.js
  src/components/Select.js
  src/components/Step.js
  src/components/TextArea.js
  src/components/Zipcode.js
Labels: enhancement

#6 Submit request flow
  build/main.js
  package-lock.json
  package.json
  spec/App.spec.js
  spec/components/Form/__snapshots__/index.spec.js.snap
  spec/components/Form/index.spec.js
  spec/components/Input.spec.js
  spec/components/Select.spec.js
  spec/components/Step.spec.js
  spec/components/TextArea.spec.js
  spec/components/Zipcode.spec.js
  spec/components/__snapshots__/Input.spec.js.snap
  spec/components/__snapshots__/Select.spec.js.snap
  spec/components/__snapshots__/Step.spec.js.snap
  spec/components/__snapshots__/TextArea.spec.js.snap
  spec/index.spec.js
  src/App.js
  src/components/Factory.js
  src/components/Form/index.js
  src/components/Form/validation.js
  src/components/Input.js
  src/components/Select.js
  src/components/Step.js
  src/components/TextArea.js
  src/components/Zipcode.js
  src/components/__mocks__/axios.js
  src/index.dev.js
  src/index.js
Labels: enhancement

#7 Remove wrapper tag
  build/main.js
  public/index.html
  spec/components/Form/__snapshots__/index.spec.js.snap
  spec/index.spec.js
  src/components/Form/index.js
  src/components/Zipcode.js
Labels: enhancement

#8 Fix ID fields
  build/main.js
  spec/components/Form/__snapshots__/index.spec.js.snap
  spec/components/Form/index.spec.js
  spec/components/__snapshots__/Step.spec.js.snap
  src/components/Factory.js
  src/components/Form/index.js
Labels: bug

#9 Set state callback
  build/main.js
  src/components/Form/index.js
Labels: enhancement, to review

#10 Add props to custom className to Field Component
  spec/components/Field.spec.js
  spec/components/Form/__snapshots__/index.spec.js.snap
  spec/components/__snapshots__/Field.spec.js.snap
  src/components/Field.js
  src/components/Step.js
  src/form.json
Labels: enhancement, to review
