Repository getninjas/jason, pull requests merged in 2018-10, with the labels that each got.

#25 External error messages and translation
  build/main.js
  spec/components/Form/__snapshots__/index.spec.js.snap
  spec/components/Form/index.spec.js
  spec/components/Form/validation.spec.js
  spec/components/Input.spec.js
  spec/components/Zipcode.spec.js
  spec/components/__snapshots__/Step.spec.js.snap
  src/components/Factory.js
  src/components/Form/index.js
  src/components/Form/validation.js
  src/components/Input.js
  src/components/Zipcode.js
  src/form.json
  src/helpers/errorMessages.js
Labels: enhancement, feature

#26 Fix minlength fetch zipcode
  package-lock.json
  package.json
  spec/helpers/zipcode.spec.js
  src/components/Zipcode.js
  src/helpers/zipcode.js
Labels: bug

#27 Fix zipcode display
  spec/components/Zipcode.spec.js
  spec/helpers/zipcode.spec.js
  src/helpers/zipcode.js
Labels: bug, to review
